commit
nikitastepnik/2022-2-VK-EDU-FS-FRONTEND-N-STEPANOV pull request #11
Opened 2022-12-29 19:05 UTC by nikitastepnik

# Домашнее задание №

Прошу преподавателей @martinkomitsky @haseprogram проверить его.  
Что было сделано:

* 

*

*

2022-12-30 18:42 UTC, martinkomitsky requested changes
Доделать

2022-12-31 02:14 UTC, nikitastepnik commented
В течение сегодняшнего дня постараюсь еще существенно доделать

2022-12-31 12:01 UTC, martinkomitsky commented
> В течение сегодняшнего дня постараюсь еще существенно доделать

Супер, только нужно еще будет пофиксить все ошибки, чтобы не было проблем с деплоем)
<img width="436" alt="image" src="https://user-images.githubusercontent.com/14847018/210135969-ea881f05-5386-4c89-8096-9ea5a807c53a.png">

2023-01-04 16:05 UTC, nikitastepnik commented
Привет, все вроде бы доделал, постарался сверстать нормально и поддержать адекватную бизнес-логику (но иногда не такую крутую, как у гугла)
Не использовал Redux и TS (так как не освоил пока, к сожалению)
Не реализовал выбор языка с помощью выпадающего меню (кажется сложным, сразу не придумаю как делать) 
Спасибо за курс!
Вы крутые! : )

2023-01-05 08:10 UTC, martinkomitsky commented
> Привет, все вроде бы доделал, постарался сверстать нормально и поддержать адекватную бизнес-логику (но иногда не такую крутую, как у гугла) Не использовал Redux и TS (так как не освоил пока, к сожалению) Не реализовал выбор языка с помощью выпадающего меню (кажется сложным, сразу не придумаю как делать) Спасибо за курс! Вы крутые! : )



Спасибо. Список делается очень просто, и думать не надо https://www.w3schools.com/tags/tag_select.asp

2023-01-05 08:13 UTC, martinkomitsky approved these changes
31

2023-01-05 08:13 UTC, merged